'use strict';

const simpleGit = require('simple-git');
const path = require('path');
const fs = require('fs-extra');
const { httpRequest } = require('../utils/http');
const logger = require('../utils/logger');

const GH_API = 'https://api.github.com';

function ghHeaders() {
  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'ai-pipeline/1.0',
  };
}

async function pushToGitHub(story, appDir) {
  const { GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO } = process.env;
  const repoUrl = `https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git`;

  const slug = story.summary
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 30);
  const branchName = `feature/${story.key}-${slug}`;

  const gitDir = path.join(path.dirname(appDir), 'git-repo');
  await fs.ensureDir(gitDir);

  // Check if remote has a main branch
  let hasRemoteMain = false;
  try {
    const refs = await simpleGit().listRemote([repoUrl]);
    hasRemoteMain = refs.includes('refs/heads/main');
  } catch {}

  const git = simpleGit(gitDir);

  if (hasRemoteMain) {
    try {
      await simpleGit().clone(repoUrl, gitDir, ['--depth', '1']);
    } catch {
      await git.init();
      try { await git.addRemote('origin', repoUrl); } catch {}
      await git.fetch('origin', 'main');
      await git.checkout('main');
    }
  } else {
    // Empty repo — bootstrap main with a README
    await git.init();
    try { await git.addRemote('origin', repoUrl); } catch {}
    await git.addConfig('user.email', 'pipeline@ai-pipeline.local');
    await git.addConfig('user.name', 'AI Pipeline Bot');
    await fs.writeFile(
      path.join(gitDir, 'README.md'),
      '# AI Automated Pipeline\n\nAuto-generated web apps.\n'
    );
    await git.add('README.md');
    await git.commit('chore: initialize repository');
    await git.push(repoUrl, 'HEAD:main');
    logger.info(`[${story.key}] Initialized empty repo`);
  }

  await git.addConfig('user.email', 'pipeline@ai-pipeline.local');
  await git.addConfig('user.name', 'AI Pipeline Bot');

  // Create feature branch
  await git.checkoutLocalBranch(branchName).catch(() => git.checkout(branchName));

  // Copy app files into the git repo (skip node_modules and test artifacts)
  for (const entry of await fs.readdir(appDir)) {
    if (entry === 'node_modules') continue;
    await fs.copy(path.join(appDir, entry), path.join(gitDir, entry), { overwrite: true });
  }
  await fs.writeFile(path.join(gitDir, '.gitignore'), 'node_modules/\n.DS_Store\n*.log\n');

  await git.add('.');
  const status = await git.status();
  if (status.files.length > 0) {
    await git.commit(`feat(${story.key}): ${story.summary}\n\nAuto-generated by AI Pipeline`);
  }

  await git.push(repoUrl, `HEAD:${branchName}`, ['--force', '--set-upstream']);
  logger.info(`[${story.key}] Pushed branch: ${branchName}`);

  const prUrl = await createPR(story, branchName, GITHUB_OWNER, GITHUB_REPO);
  return { prUrl, branchName };
}

async function createPR(story, branchName, owner, repo) {
  try {
    const { data } = await httpRequest(`${GH_API}/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: ghHeaders(),
      body: {
        title: `feat(${story.key}): ${story.summary}`,
        head: branchName,
        base: 'main',
        body: `## AI-Generated Application\n\n**Jira Story:** ${story.key}\n**Summary:** ${story.summary}\n\nAuto-created by the AI Pipeline.`,
      },
    });
    logger.info(`[${story.key}] PR created: ${data.html_url}`);
    return data.html_url;
  } catch (err) {
    if (err.statusCode === 422) {
      // PR already exists — find and return it
      const { data } = await httpRequest(
        `${GH_API}/repos/${owner}/${repo}/pulls?head=${owner}:${branchName}&state=open`,
        { headers: ghHeaders() }
      );
      if (data.length) return data[0].html_url;
    }
    throw err;
  }
}

module.exports = { pushToGitHub };
